import { IngredientKnowledge } from '../types.js';

export const CEREAL_INGREDIENTS: IngredientKnowledge[] = [
  {
    id: 'whole_wheat_flour',
    canonicalName: 'Whole Wheat Flour (Atta)',
    aliases: ['atta', 'chakki atta', 'chakki fresh atta', 'gehun ka atta', 'whole wheat flour', 'wholewheat flour', 'whole meal wheat flour', 'wholemeal flour', '100% whole wheat', 'whole wheat'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'gluten',
    description: 'Coarsely or stone-ground flour obtained from milling whole wheat grains including the bran, germ, and endosperm.',
    sourceRefs: ['FSSAI Food Safety Standards Regulations 2.4.1', 'ICMR-NIN Dietary Guidelines 2024']
  },
  {
    id: 'refined_wheat_flour',
    canonicalName: 'Refined Wheat Flour (Maida)',
    aliases: ['maida', 'refined wheat flour', 'refined flour', 'all purpose flour', 'all-purpose flour', 'white flour', 'bleached flour', 'wheat flour (maida)', 'refined wheat flour (maida)'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: true,
    isPositiveMarker: false,
    allergenType: 'gluten',
    description: 'Finely milled, refined wheat endosperm with the bran and germ removed, resulting in lower dietary fiber and micronutrients.',
    sourceRefs: ['FSSAI Food Safety Standards Regulations 2.4.2']
  },
  {
    id: 'semolina',
    canonicalName: 'Semolina (Sooji / Rava)',
    aliases: ['sooji', 'suji', 'rava', 'bombay rava', 'semolina', 'durum wheat semolina', 'wheat semolina', 'rawa'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'gluten',
    description: 'Coarse purified wheat middlings of durum or bread wheat used widely in Indian savory and sweet dishes.',
    sourceRefs: ['FSSAI Standards 2.4.3']
  },
  {
    id: 'finger_millet',
    canonicalName: 'Finger Millet (Ragi)',
    aliases: ['ragi', 'nachni', 'finger millet', 'mandua', 'kezhvaragu', 'ragulu', 'ragi flour', 'sprouted ragi'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Nutrient-dense ancient Indian millet rich in dietary fiber, polyphenols, and calcium (~344mg/100g).',
    sourceRefs: ['ICMR-NIN Indian Food Composition Tables', 'FSSAI Millets Standard']
  },
  {
    id: 'pearl_millet',
    canonicalName: 'Pearl Millet (Bajra)',
    aliases: ['bajra', 'pearl millet', 'sajje', 'kambu', 'sajjalu', 'bajra flour', 'sprouted bajra'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional Indian climate-resilient millet rich in iron, zinc, protein, and dietary fiber.',
    sourceRefs: ['ICMR-NIN IFCT 2017', 'FSSAI Millets Standard']
  },
  {
    id: 'sorghum',
    canonicalName: 'Sorghum (Jowar)',
    aliases: ['jowar', 'sorghum', 'cholam', 'jonna', 'jowar flour', 'great millet'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Naturally gluten-free whole millet packed with complex carbohydrates, antioxidants, and dietary fiber.',
    sourceRefs: ['ICMR-NIN Dietary Guidelines 2024']
  },
  {
    id: 'foxtail_millet',
    canonicalName: 'Foxtail Millet (Kangni)',
    aliases: ['kangni', 'kakum', 'foxtail millet', 'navane', 'tenai', 'korra'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Ancient positive millet recognized for low glycemic index and high dietary fiber content.',
    sourceRefs: ['FSSAI Shree Anna Millets Framework']
  },
  {
    id: 'kodo_millet',
    canonicalName: 'Kodo Millet (Kodon)',
    aliases: ['kodo', 'kodon', 'kodo millet', 'varagu', 'arikalu', 'harka'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional whole grain millet with high antioxidant and dietary fiber profile.',
    sourceRefs: ['FSSAI Shree Anna Millets Framework']
  },
  {
    id: 'barnyard_millet',
    canonicalName: 'Barnyard Millet (Sanwa)',
    aliases: ['sanwa', 'samvat', 'jhangora', 'barnyard millet', 'kuthiraivally', 'odalu'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Fast-growing nutritious millet frequently used in traditional Indian fasting and wholesome preparations.',
    sourceRefs: ['FSSAI Shree Anna Millets Framework']
  },
  {
    id: 'little_millet',
    canonicalName: 'Little Millet (Kutki)',
    aliases: ['kutki', 'little millet', 'samai', 'same', 'shavan', 'sama'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Small-seeded whole grain millet rich in B-vitamins, calcium, iron, and zinc.',
    sourceRefs: ['FSSAI Shree Anna Millets Framework']
  },
  {
    id: 'oats',
    canonicalName: 'Whole Oats / Rolled Oats',
    aliases: ['oats', 'rolled oats', 'oat flakes', 'whole oats', 'oatmeal', 'oat flour', 'wholegrain oats', 'quick cooking oats'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'gluten',
    description: 'Whole cereal grain rich in beta-glucan soluble dietary fiber, known to help support heart and metabolic health.',
    sourceRefs: ['FSSAI Standards 2.4.17']
  },
  {
    id: 'brown_rice',
    canonicalName: 'Brown Rice',
    aliases: ['brown rice', 'whole brown rice', 'unpolished rice', 'brown rice flour'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Whole grain rice retaining the outer bran layer and germ, offering higher fiber and minerals than polished white rice.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'white_rice',
    canonicalName: 'White Rice / Rice Flour',
    aliases: ['rice', 'white rice', 'polished rice', 'rice flour', 'milled rice', 'rice powder'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Milled cereal grain where the outer husk, bran, and germ have been removed.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'flattened_rice',
    canonicalName: 'Flattened Rice (Poha / Aval)',
    aliases: ['poha', 'aval', 'flattened rice', 'beaten rice', 'chiwda', 'chira', 'pressed rice'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'De-husked parboiled rice rolled and flattened into light dry flakes, widely consumed across India.',
    sourceRefs: ['FSSAI Standards']
  },
  {
    id: 'puffed_rice',
    canonicalName: 'Puffed Rice (Murmura)',
    aliases: ['murmura', 'kurmura', 'puffed rice', 'pori', 'muri'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Expanded rice grains puffed using high-temperature steam or roasting.',
    sourceRefs: ['FSSAI Standards']
  },
  {
    id: 'corn_flour',
    canonicalName: 'Corn Flour / Maize Starch',
    aliases: ['corn flour', 'corn starch', 'maize starch', 'cornstarch', 'makki ka atta', 'maize flour'],
    category: 'refined_cereal',
    isWholeGrain: false,
    isRefinedGrain: true,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Refined starch or flour extracted from the endosperm of the corn kernel, commonly used as a thickener and binder.',
    sourceRefs: ['FSSAI Standards 2.4.8']
  },
  {
    id: 'barley',
    canonicalName: 'Barley (Jau)',
    aliases: ['barley', 'jau', 'pearl barley', 'barley flour', 'whole barley'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'gluten',
    description: 'Nutritious whole grain rich in beta-glucan soluble fiber and essential minerals.',
    sourceRefs: ['FSSAI Standards 2.4.11']
  },
  {
    id: 'quinoa',
    canonicalName: 'Quinoa',
    aliases: ['quinoa', 'whole quinoa', 'quinoa flour', 'quinoa seeds'],
    category: 'whole_grain',
    isWholeGrain: true,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Pseudo-cereal offering a complete amino acid protein profile and high dietary fiber.',
    sourceRefs: ['FAO Quinoa Assessment']
  }
];
