import { IngredientKnowledge } from '../types.js';

export const OIL_INGREDIENTS: IngredientKnowledge[] = [
  {
    id: 'palmolein',
    canonicalName: 'Refined Palmolein Oil',
    aliases: ['palmolein', 'refined palmolein', 'palmolein oil', 'refined palmolein oil', 'fractionated palmolein', 'edible vegetable oil (palmolein)', 'edible vegetable oil (refined palmolein)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: true,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Liquid fraction obtained from fractionation of palm oil; high in saturated fatty acids (~45-50%). Dominant industrial oil in Indian packaged snacks.',
    sourceRefs: ['FSSAI Standards 2.2.1.22', 'WHO Saturated Fat Guidelines']
  },
  {
    id: 'palm_oil',
    canonicalName: 'Palm Oil / Palm Fat',
    aliases: ['palm oil', 'refined palm oil', 'edible palm oil', 'palm fat', 'fractionated palm fat', 'edible vegetable oil (palm oil)', 'edible vegetable oil (palm)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: true,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Edible oil derived from the mesocarp of oil palm fruit; high in palmitic acid and saturated fats.',
    sourceRefs: ['FSSAI Standards 2.2.1.21']
  },
  {
    id: 'hydrogenated_vegetable_oil',
    canonicalName: 'Hydrogenated Vegetable Oil (Vanaspati)',
    aliases: ['vanaspati', 'dalda', 'hydrogenated vegetable oil', 'hydrogenated vegetable fat', 'partially hydrogenated vegetable oil', 'partially hydrogenated fat', 'hydrogenated fat', 'vegetable shortening'],
    category: 'hydrogenated_fat',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: true,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Vegetable oil processed through industrial hydrogenation to solidify; historical source of industrial trans-fatty acids (capped at 2% by FSSAI).',
    sourceRefs: ['FSSAI Trans Fat Regulations 2022', 'WHO REPLACE Action Package']
  },
  {
    id: 'mustard_oil',
    canonicalName: 'Mustard Oil (Kachi Ghani)',
    aliases: ['mustard oil', 'kachi ghani mustard oil', 'cold pressed mustard oil', 'sarson ka tel', 'raw mustard oil', 'edible vegetable oil (mustard)'],
    category: 'cold_pressed_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'mustard',
    description: 'Traditional pungent Indian cooking oil pressed from mustard seeds; rich in monounsaturated fats (MUFA) and alpha-linolenic acid (Omega-3).',
    sourceRefs: ['FSSAI Standards 2.2.1.6', 'ICMR-NIN Dietary Guidelines']
  },
  {
    id: 'groundnut_oil',
    canonicalName: 'Groundnut / Peanut Oil',
    aliases: ['groundnut oil', 'peanut oil', 'sing tel', 'moongfali tel', 'cold pressed groundnut oil', 'edible vegetable oil (groundnut)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'peanuts',
    description: 'Nutty edible oil expressed from groundnuts; naturally balanced in monounsaturated and polyunsaturated fatty acids.',
    sourceRefs: ['FSSAI Standards 2.2.1.8']
  },
  {
    id: 'sesame_oil',
    canonicalName: 'Sesame Oil (Gingelly / Til Oil)',
    aliases: ['sesame oil', 'gingelly oil', 'til oil', 'til ka tel', 'cold pressed sesame oil', 'edible vegetable oil (sesame)'],
    category: 'cold_pressed_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'sesame',
    description: 'Traditional oil rich in natural antioxidants (sesamol, sesamin) and balanced unsaturated fatty acids.',
    sourceRefs: ['FSSAI Standards 2.2.1.7']
  },
  {
    id: 'coconut_oil',
    canonicalName: 'Coconut Oil',
    aliases: ['coconut oil', 'nariyal tel', 'virgin coconut oil', 'cold pressed coconut oil', 'edible coconut oil'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Traditional tropical edible oil pressed from copra or fresh coconut; predominantly medium-chain saturated fatty acids (lauric acid).',
    sourceRefs: ['FSSAI Standards 2.2.1.1']
  },
  {
    id: 'sunflower_oil',
    canonicalName: 'Sunflower Oil',
    aliases: ['sunflower oil', 'refined sunflower oil', 'sunflower seed oil', 'edible vegetable oil (sunflower)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Widely used light vegetable oil high in polyunsaturated fatty acids (linoleic acid) and Vitamin E.',
    sourceRefs: ['FSSAI Standards 2.2.1.10']
  },
  {
    id: 'soybean_oil',
    canonicalName: 'Soybean Oil',
    aliases: ['soybean oil', 'refined soybean oil', 'soya oil', 'edible vegetable oil (soybean)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'soy',
    description: 'Common vegetable cooking oil offering polyunsaturated Omega-6 and Omega-3 fatty acids.',
    sourceRefs: ['FSSAI Standards 2.2.1.14']
  },
  {
    id: 'rice_bran_oil',
    canonicalName: 'Rice Bran Oil',
    aliases: ['rice bran oil', 'refined rice bran oil', 'edible vegetable oil (rice bran)'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Heart-friendly vegetable oil extracted from the hard outer brown layer of rice; contains unique antioxidant oryzanol.',
    sourceRefs: ['FSSAI Standards 2.2.1.20']
  },
  {
    id: 'olive_oil',
    canonicalName: 'Olive Oil',
    aliases: ['olive oil', 'extra virgin olive oil', 'virgin olive oil', 'olive pomace oil', 'refined olive oil'],
    category: 'cold_pressed_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Mediterranean oil rich in heart-healthy monounsaturated oleic acid and phenolic antioxidants.',
    sourceRefs: ['FSSAI Standards 2.2.1.17', 'Codex Standard for Olive Oils']
  },
  {
    id: 'ghee',
    canonicalName: 'Clarified Butter (Desi Ghee)',
    aliases: ['ghee', 'desi ghee', 'clarified butter', 'cow ghee', 'pure ghee', 'milk fat', 'butter oil'],
    category: 'dairy',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'milk',
    description: 'Traditional Indian clarified dairy fat produced by simmering butter; rich in fat-soluble vitamins (A, D, E) and butyric acid.',
    sourceRefs: ['FSSAI Standards 2.1.8', 'ICMR-NIN Guidelines']
  },
  {
    id: 'butter',
    canonicalName: 'Butter',
    aliases: ['butter', 'dairy butter', 'pasteurized butter', 'table butter', 'white butter', 'makhan'],
    category: 'dairy',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'milk',
    description: 'Dairy emulsion made by churning cream; contains approximately 80% milk fat.',
    sourceRefs: ['FSSAI Standards 2.1.6']
  },
  {
    id: 'cocoa_butter',
    canonicalName: 'Cocoa Butter',
    aliases: ['cocoa butter', 'edible cocoa butter', 'cacao butter'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Pure edible plant fat extracted from whole cocoa beans, giving chocolate its melt-in-mouth texture.',
    sourceRefs: ['FSSAI Standards 2.7.4']
  },
  {
    id: 'interesterified_vegetable_fat',
    canonicalName: 'Interesterified Vegetable Fat',
    aliases: ['interesterified vegetable fat', 'interesterified fat', 'blended vegetable fat'],
    category: 'refined_oil',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: true,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Industrial chemically or enzymatically modified fat blend designed to replace trans-fatty shortenings.',
    sourceRefs: ['FSSAI Standards 2.2.2']
  }
];
