import { IngredientKnowledge } from '../types.js';

export const PULSE_INGREDIENTS: IngredientKnowledge[] = [
  {
    id: 'chickpea_flour',
    canonicalName: 'Chickpea Flour (Besan / Gram Flour)',
    aliases: ['besan', 'gram flour', 'bengal gram flour', 'chickpea flour', 'chana flour', 'kadale hittu', 'senaga pindi'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Flour prepared by milling dried chickpeas or split Bengal gram; rich in plant protein and dietary fiber.',
    sourceRefs: ['FSSAI Standards 2.4.16', 'ICMR-NIN IFCT 2017']
  },
  {
    id: 'chickpeas',
    canonicalName: 'Whole Chickpeas (Chana)',
    aliases: ['chana', 'kabuli chana', 'kala chana', 'chickpeas', 'garbanzo beans', 'white chickpeas', 'black chickpeas'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'High-protein legume providing complex carbohydrates, iron, folate, and dietary fiber.',
    sourceRefs: ['ICMR-NIN Dietary Guidelines']
  },
  {
    id: 'pigeon_peas',
    canonicalName: 'Pigeon Peas (Toor / Tuvar Dal)',
    aliases: ['toor dal', 'tuvar dal', 'arhar dal', 'pigeon peas', 'red gram split', 'tuvar', 'arhar'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Primary staple Indian dal providing dietary protein, potassium, and magnesium.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'split_chickpea',
    canonicalName: 'Split Bengal Gram (Chana Dal)',
    aliases: ['chana dal', 'split chickpea', 'bengal gram split', 'split bengal gram'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Split and polished Bengal gram with a low glycemic index and high protein concentration.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'mung_beans',
    canonicalName: 'Mung Beans (Moong Dal)',
    aliases: ['moong dal', 'mung dal', 'green gram', 'yellow moong', 'green moong', 'mung beans', 'split green gram'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Easily digestible Indian legume with high protein bioavailability and essential amino acids.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'black_gram',
    canonicalName: 'Black Gram (Urad Dal)',
    aliases: ['urad dal', 'black gram', 'dhuli urad', 'split black gram', 'white urad dal', 'black matpe'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Dense legume widely used in traditional batters (idli/dosa) and dals; rich in calcium and iron.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'red_lentils',
    canonicalName: 'Red Lentils (Masoor Dal)',
    aliases: ['masoor dal', 'red lentils', 'split red lentils', 'whole masoor', 'pink lentils'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Quick-cooking red lentils providing high protein, soluble fiber, and B-vitamins.',
    sourceRefs: ['FSSAI Standards 2.4.6']
  },
  {
    id: 'green_peas',
    canonicalName: 'Green Peas (Matar)',
    aliases: ['peas', 'green peas', 'matar', 'dried peas', 'pea protein', 'pea flour'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Nutritious pulse rich in vitamin A, vitamin C, iron, and plant-based protein.',
    sourceRefs: ['ICMR-NIN IFCT 2017']
  },
  {
    id: 'soybeans',
    canonicalName: 'Soybean / Soya Protein',
    aliases: ['soy', 'soya', 'soybeans', 'soya chunks', 'defatted soya flour', 'soy protein isolate', 'soya granules', 'textured vegetable protein'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'soy',
    description: 'Legume offering an exceptionally high complete protein profile and isoflavones.',
    sourceRefs: ['FSSAI Standards 2.4.21']
  },
  {
    id: 'kidney_beans',
    canonicalName: 'Kidney Beans (Rajma)',
    aliases: ['rajma', 'kidney beans', 'red kidney beans', 'chitra rajma'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional legume rich in plant protein, complex carbohydrates, iron, and potassium.',
    sourceRefs: ['ICMR-NIN IFCT 2017']
  },
  {
    id: 'moth_beans',
    canonicalName: 'Moth Bean (Moth Dal / Matki / Tepary Bean)',
    aliases: ['moth dal', 'moth bean', 'moth flour', 'tepary bean', 'matki', 'moth', 'moth pulse flour', 'tepary bean flour'],
    category: 'pulse_legume',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Drought-hardy Indian legume packed with plant protein (approx 22-24%), magnesium, and calcium, widely used in traditional Bhujia savouries.',
    sourceRefs: ['ICMR-NIN Indian Food Composition Tables 2017', 'FSSAI Standards 2.4.6']
  }
];
