import { IngredientKnowledge } from '../types.js';

export const VEGETABLE_SPICE_INGREDIENTS: IngredientKnowledge[] = [
  {
    id: 'iodized_salt',
    canonicalName: 'Iodized Salt (Edible Common Salt)',
    aliases: ['salt', 'edible common salt', 'iodized salt', 'table salt', 'namak', 'iodised salt', 'common salt', 'rock salt', 'sendha namak', 'kala namak', 'black salt'],
    category: 'salt',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Edible sodium chloride fortified with iodine in compliance with Indian universal salt iodization mandates.',
    sourceRefs: ['FSSAI Standards 2.9.30']
  },
  {
    id: 'cocoa_solids',
    canonicalName: 'Cocoa Solids / Cocoa Powder',
    aliases: ['cocoa solids', 'cocoa powder', 'defatted cocoa', 'cocoa mass', 'cocoa liquor', 'cacao powder'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Dry solids remaining after extracting cocoa butter from fermented, roasted cocoa beans; rich in polyphenol flavanols.',
    sourceRefs: ['FSSAI Standards 2.7.4']
  },
  {
    id: 'tomato_paste',
    canonicalName: 'Tomato Paste / Puree',
    aliases: ['tomato paste', 'tomato puree', 'tomato solids', 'concentrated tomato paste', 'tomato powder', 'tomatoes'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Concentrated tomato pulp providing dietary lycopene, potassium, and Vitamin C.',
    sourceRefs: ['FSSAI Standards 2.3.28']
  },
  {
    id: 'turmeric',
    canonicalName: 'Turmeric (Haldi)',
    aliases: ['turmeric', 'haldi', 'turmeric powder', 'curcuma longa', 'haldi powder'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional golden Indian rhizome spice packed with natural curcuminoid antioxidants.',
    sourceRefs: ['FSSAI Standards 2.9.11']
  },
  {
    id: 'ginger',
    canonicalName: 'Ginger (Adrak / Sonth)',
    aliases: ['ginger', 'adrak', 'dry ginger', 'ginger powder', 'sonth', 'fresh ginger'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional rhizome spice rich in gingerols and digestive bioactives.',
    sourceRefs: ['FSSAI Standards 2.9.10']
  },
  {
    id: 'garlic_powder',
    canonicalName: 'Garlic / Garlic Powder',
    aliases: ['garlic', 'garlic powder', 'lahsun', 'dehydrated garlic', 'dried garlic flakes'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Aromatic allium bulb offering sulfur bioactives (allicin) and savory culinary depth.',
    sourceRefs: ['FSSAI Standards 2.9.36']
  },
  {
    id: 'onion_powder',
    canonicalName: 'Onion / Onion Powder',
    aliases: ['onion', 'onion powder', 'pyaz', 'dehydrated onion', 'dried onion flakes'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Dehydrated allium vegetable rich in prebiotic fructooligosaccharides and quercetin.',
    sourceRefs: ['FSSAI Standards 2.9.35']
  },
  {
    id: 'cumin',
    canonicalName: 'Cumin (Jeera)',
    aliases: ['cumin', 'jeera', 'cumin powder', 'roasted cumin', 'zeera'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Popular aromatic Indian seed spice containing essential oils and digestive stimulants.',
    sourceRefs: ['FSSAI Standards 2.9.8']
  },
  {
    id: 'coriander',
    canonicalName: 'Coriander (Dhania)',
    aliases: ['coriander', 'dhania', 'coriander powder', 'coriander seeds'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Traditional spice seed providing warm citrusy flavor and dietary bioflavonoids.',
    sourceRefs: ['FSSAI Standards 2.9.7']
  },
  {
    id: 'red_chilli',
    canonicalName: 'Red Chilli (Lal Mirch)',
    aliases: ['chilli', 'red chilli', 'lal mirch', 'chili powder', 'red pepper', 'paprika', 'paprika extract'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Pungent dried capsicum fruit spice containing capsaicin and carotenoids.',
    sourceRefs: ['FSSAI Standards 2.9.6']
  },
  {
    id: 'cardamom',
    canonicalName: 'Cardamom (Elaichi)',
    aliases: ['cardamom', 'elaichi', 'green cardamom', 'cardamom powder', 'elachi'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Queen of Indian spices; aromatic seed pods rich in cineole and terpenes.',
    sourceRefs: ['FSSAI Standards 2.9.1']
  },
  {
    id: 'cinnamon',
    canonicalName: 'Cinnamon (Dalchini)',
    aliases: ['cinnamon', 'dalchini', 'cinnamon powder', 'cassia'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Aromatic tree bark spice packed with cinnamaldehyde and polyphenols.',
    sourceRefs: ['FSSAI Standards 2.9.4']
  },
  {
    id: 'mango_pulp',
    canonicalName: 'Mango Pulp / Puree',
    aliases: ['mango pulp', 'alphonso mango pulp', 'mango puree', 'concentrated mango juice', 'totapuri mango pulp'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Pure fruit pulp extracted from fresh ripe Indian mangoes; natural source of beta-carotene.',
    sourceRefs: ['FSSAI Standards 2.3.10']
  },
  {
    id: 'lemon_juice',
    canonicalName: 'Lemon Juice / Lime Concentrate',
    aliases: ['lemon juice', 'lime juice', 'concentrated lemon juice', 'nimbu ras', 'lemon juice concentrate', 'orange juice concentrate'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: true,
    allergenType: 'none',
    description: 'Citrus juice rich in natural citric acid and Vitamin C.',
    sourceRefs: ['FSSAI Standards 2.3.6']
  },
  {
    id: 'potato',
    canonicalName: 'Potato (Aloo)',
    aliases: ['potato', 'potatoes', 'dehydrated potato', 'potato flakes', 'potato starch', 'aloo', 'aloo flakes', 'potato powder'],
    category: 'vegetable_fruit',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Starchy tuber widely consumed as a vegetable and whole food base in Indian savoury foods.',
    sourceRefs: ['FSSAI Standards', 'ICMR-NIN IFCT 2017']
  },
  {
    id: 'water',
    canonicalName: 'Water',
    aliases: ['water', 'purified water', 'carbonated water', 'drinking water', 'treated water', 'mineral water', 'pani'],
    category: 'general',
    isWholeGrain: false,
    isRefinedGrain: false,
    isUltraProcessedMarker: false,
    isPositiveMarker: false,
    allergenType: 'none',
    description: 'Potable water or carbonated water compliant with Indian drinking water standards (IS 10500).',
    sourceRefs: ['IS 10500 Drinking Water Specification', 'FSSAI Standards']
  }
];
